it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    cookiebar_accept: Accetto
    cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
    cookiebar_privacy_policy: Privacy policy
    follow_us: seguici su
    header_link_pt: Piano Triennale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: Github
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy
    footer_link_legal_notes: note legali
    footer_link_credits: crediti
    footer_title: ''
    in_collaboration_with: In collaborazione con
    footer_note: Cover image courtesy of [Matteo Vistocco](https://unsplash.com/@biscuits94)
    footer_public_domain: Donazione al Pubblico Dominio
    lang_on_site: sito in italiano
    navigation_network_menu_label: Menu di navigazione del network
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    site_subtitle: "per l'informatica nella Pubblica Amministrazione"
    site_title: Piano Triennale
    site_title_mobile: Piano Triennale ICT
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
    toggle_menu_label: accedi al menu
    toggle_network_menu_label: accedi al menu del network
    see_more: per saperne di più
    goto_chapter: vai al capitolo
    goto_chapter_en: read the chapter
    goto_forum: partecipa
    deepen: per approfondire
    download_chapter: scarica il capitolo
    discuss: per confrontarti
    cap_on_github: vai al capitolo su github
    by: di
    on_: "su"
    actions: le azioni
    amministrazioni_centrali: amministrazioni centrali
    amministrazioni_territoriali: amministrazioni territoriali
    tempi: tempi
    attori: attori
    descrizione: descrizione
    risultati: risultati
    completata: completata
    home_hero: |
      «La trasformazione digitale è una priorità del Governo.
      Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
    home_hero_mobile: |
      «La trasformazione digitale è una priorità del Governo.
      Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
    home_tools_title: Strumenti
    home_tools_subtitle: Ci appoggiamo a strumenti già esistenti e molto conosciuti per fornirti le informazioni, il codice e il supporto di cui hai bisogno
    home_header_button_text: vai al piano
    home_header_button_text_en: go to plan
    home_pt_title: Cos'è il Piano Triennale
    home_pt_description: |
      È il documento di indirizzo strategico ed economico destinato a tutta la Pubblica Amministrazione che accompagna la trasformazione digitale del Paese.

      Il Piano definisce:
      - le linee operative di sviluppo dell’informatica pubblica;
      - il Modello strategico di evoluzione del sistema informativo della PA;
      - gli investimenti ICT del settore pubblico secondo le linee guida europee e del Governo.
    home_pt_howto_title: Consulta il Piano
    home_pt_howto:
      - text: |
         Nelle pagine di questo sito vengono riassunti i contenuti del Piano Triennale, suddivisi per [capitoli](/piano) e [azioni](/azioni).
         Il documento completo è disponibile online in versione navigabile ottimizzata per dispositivi mobili o in PDF.
        links:
          - type: button
            icon: read
            label: Versione navigabile
            href: 'https://pianotriennale-ict.readthedocs.io/'
            target_blank: true
          - icon: download-alt
            label: scarica il pdf
            href: '/assets/pdf/Piano_Triennale_per_l_informatica_nella_Pubblica_Amministrazione.pdf'
            target_blank: true
      - text: Hai bisogno di chiarimenti? Consulta le [FAQ](/faq), partecipa al forum di discussione dedicato oppure proponi una modifica al testo su [GitHub](https://github.com/italia/pianotriennale-ict-doc).
        links:
          - type: button
            icon: forum
            label: partecipa
            href: 'https://forum.italia.it/c/piano-triennale'
            target_blank: true
    home_pt_en_title: The Three Year Plan
    home_pt_en:
      - text: It was translated by Artificial Intelligence. It is available online on mobile optimized navigation.
        links:
          - type: button
            icon: read
            label: Read It
            href: 'https://pianotriennale-ict.readthedocs.io/en'
            target_blank: true
    quotes:
      gentiloni:
        text: |
          «La trasformazione digitale è una priorità del Governo. Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
        text_short: |
          «La trasformazione digitale è una priorità del Governo. Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
        author_name: Paolo Gentiloni
        author_role: Presidente del Consiglio dei Ministri
      madia:
        text: |
          «Con il Piano Triennale prosegue la trasformazione digitale che permetterà alle pubbliche amministrazioni di diventare più efficienti e mettere il cittadino al centro delle loro azioni. L’aggiornamento del Codice dell’Amministrazione Digitale sarà un ulteriore passo per liberare l’innovazione dai troppi regolamenti e rafforzare i diritti di cittadinanza digitale»
        text_short: |
          «Con il Piano Triennale prosegue la trasformazione digitale che permetterà alle pubbliche amministrazioni di diventare più efficienti e mettere il cittadino al centro delle loro azioni. L’aggiornamento del Codice dell’Amministrazione Digitale sarà un ulteriore passo per liberare l’innovazione dai troppi regolamenti e rafforzare i diritti di cittadinanza digitale»
        author_name: Marianna Madia
        author_role: Ministro per la semplificazione e la Pubblica Amministrazione
      piacentini:
        text: |
          «Stiamo introducendo una modalità di partecipazione completamente nuova, certi che per raggiungere l’obiettivo della trasformazione digitale dei servizi della Pubblica Amministrazione si debba agire in maniera collaborativa»
        text_short: |
          «Stiamo introducendo una modalità di partecipazione completamente nuova, certi che per raggiungere l’obiettivo della trasformazione digitale dei servizi della Pubblica Amministrazione si debba agire in maniera collaborativa»
        author_name: Diego Piacentini
        author_role: Commissario straordinario per l'attuazione dell'Agenda Digitale
        goto_link: 'https://medium.com/@diegopia/piano-triennale-trasformazione-digitale-pubblica-amministrazione-linee-guida-design-sviluppo-open-source-a54e27d55be9'
        goto_label: Leggi il post completo su Medium
    capitoli_title: Tutti i capitoli del piano
    capitoli:
      data-center-e-cloud: Data center e cloud
      connettivita: Connettività
      dati-della-pa: Dati della PA
      piattaforme-abilitanti: Piattaforme abilitanti
      modello-di-interoperabilita: Modello di interoperabilità
      ecosistemi: Ecositemi
      strumenti-per-la-generazione-e-la-diffusione-di-servizi-digitali: Strumenti per la generazione e la diffusione di servizi digitali
      sicurezza: Sicurezza
      data-analytics-framework: Data & Analytics Framework
      gestione-del-cambiamento: Gestione del cambiamento
      principi-per-lo-sviluppo-di-progetti-digitali: Principi per lo sviluppo di progetti digitali
      razionalizzazione-della-spesa: Razionalizzazione della spesa
      piano-triennale: Piano Triennale
      modello-strategico: Modello strategico
      indicazioni-per-le-pa: Indicazioni per le PA
    capitoli_en:
      data-center-e-cloud: Data centres and cloud
      connettivita: Connectivity
      dati-della-pa: Public Administration Data
      piattaforme-abilitanti: Enabling platforms
      modello-di-interoperabilita: Interoperability Model
      ecosistemi: Ecosystems
      strumenti-per-la-generazione-e-la-diffusione-di-servizi-digitali: Instruments for the generation and the spread of digital services
      sicurezza: Security
      data-analytics-framework: Data & Analytics Framework
      gestione-del-cambiamento: Management of the change
      principi-per-lo-sviluppo-di-progetti-digitali: Principles for the development of digital projects
      razionalizzazione-della-spesa: Rationalisation of costs
      piano-triennale: Three-Year Plan for IT in Public Administration
      modello-strategico: Strategic evolution model of the information system of the public administration
      indicazioni-per-le-pa: Indications for the Public administrations
    temi_title: I capitoli
    modello_intro: Clicca sulla sezione che ti interessa
    partecipa: Partecipa
    forum_intro: "Chiunque può partecipare al forum di discussione e contribuire alla diffusione e all'implementazione' del Piano Triennale."
    temi:
      servizi-digitali: Servizi digitali
      ecosistemi: Ecosistemi
      interoperabilita: Interoperabilità
      piattaforme-abilitanti: Piattaforme abilitanti
      dati: Dati
      rete: Connettività
      cloud: Data center e cloud
      sicurezza: Sicurezza
      big-data: Data & Analytics Framework
      gestione-del-cambiamento: Gestione del cambiamento
