it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    cookiebar_accept: Accetto
    cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
    cookiebar_privacy_policy: Privacy policy
    follow_us: seguici su
    header_link_trasformazione: Trasformazione digitale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: Github
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy
    footer_link_legal_notes: note legali
    footer_link_credits: crediti
    footer_title: ''
    in_collaboration_with: In collaborazione con
    footer_note: Cover image courtesy of [Matteo Vistocco](https://unsplash.com/@biscuits94)
    footer_public_domain: Donazione al Pubblico Dominio
    lang_on_site: sito in italiano
    navigation_network_menu_label: Menu di navigazione del network
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    site_subtitle: Piano triennale per l'informatica nella pubblica amministrazione
    site_title: Trasformazione digitale
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
    toggle_menu_label: accedi al menu
    toggle_network_menu_label: accedi al menu del network
    see_more: per saperne di più
    goto_chapter: vai al capitolo
    goto_forum: vai al forum
    deepen: per approfondire
    download_chapter: scarica il capitolo
    discuss: per confrontarti
    cap_on_github: vai al capitolo su github
    by: di
    on_: "su"
    actions: le azioni
    amministrazioni_centrali: amministrazioni centrali
    amministrazioni_locali: amministrazioni locali
    tempi: tempi
    attori: attori
    descrizione: descrizione
    risultati: risultati
    home_hero: |
      Semplifichiamo la vita dei cittadini
      grazie alla tecnologia, alle competenze
      e al gioco di squadra.
    home_hero_mobile: |
      Semplifichiamo
      la vita dei cittadini
      grazie alla tecnologia,
      alle competenze e al
      gioco di squadra.
    home_tools_title: Strumenti
    home_tools_subtitle: Ci appoggiamo a strumenti già esistenti e molto conosciuti per fornirti le informazioni, il codice e il supporto di cui hai bisogno
    home_header_button_text: vai al piano
    home_pt_title: Cos'è il Piano Triennale
    home_pt_description: |
      È un documento di programmazione che ha lo scopo di:
      - contribuire alla crescita dell’economia del Paese accompagnando la trasformazione digitale delle pubbliche amministrazioni;
      - indirizzare gli investimenti ICT del settore pubblico secondo le linee guida del Governo, in coerenza con le direttive europee;
      - individuare i risparmi previsti nella Legge di Stabilità 2016.
    home_pt_howto_title: Come si usa
    home_pt_howto:
      - text: "Il documento è disponibile online: in versione navigabile ottimizzata per dispositivi mobili oppure come pdf."
        links:
          - type: button
            icon: read
            label: vai al piano
            href: 'https://pianotriennale-ict.readthedocs.io/'
            target_blank: true
          - icon: download-alt
            label: scarica il pdf
            href: '/assets/pdf/Piano_Triennale_per_l_informatica_nella_Pubblica_Amministrazione.pdf'
            target_blank: true
      - text: Chiunque può chiedere chiarimenti o proporre integrazioni partecipando al forum di discussione oppure proponendo una modifica al testo su GitHub.
        links:
          - type: button
            icon: forum
            label: vai al forum
            href: 'https://forum.developers.italia.it/c/piano-triennale'
            target_blank: true

    quotes:
      gentiloni:
        text: |
          «Ambitioni dedisse scripsisse iudicaretur. Salutantibus vitae elit libero, a pharetra augue. Fabio vel iudice vincam, sunt in culpa qui officia. Prima luce, cum quibus mons aliud consensu ab eo. At nos hinc posthac, sitientis piros Afros. Petierunt uti sibi concilium totius Galliae in diem certam indicere.
          Gallia est omnis divisa in partes tres, quarum. Cras mattis iudicium purus sit amet fermentum. Qui ipsorum lingua Celtae, nostra Galli appellantur. Excepteur sint obcaecat cupiditat non proident culpa.
          Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. Quisque ut dolor gravida, placerat libero vel, euismod. Quo usque tandem abutere, Catilina, patientia nostra? A communi observantia non est recedendum. Inmensae subtilitatis, obscuris et malesuada fames. Unam incolunt Belgae, aliam Aquitani, tertiam.»
        text_short: |
          «Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus sit amet orci eget imperdiet. Mauris tristique enim faucibus, lobortis mauris ut, aliquam justo.
          Suspendisse consequat id sem ut suscipit. Sed congue dolor enim, eu tristique dolor pulvinar ac.»
        author_name: Paolo Gentiloni
        author_role: Presidente del Consiglio dei Ministri
      madia:
        text: |
          «Ambitioni dedisse scripsisse iudicaretur. Salutantibus vitae elit libero, a pharetra augue. Fabio vel iudice vincam, sunt in culpa qui officia. Prima luce, cum quibus mons aliud consensu ab eo. At nos hinc posthac, sitientis piros Afros. Petierunt uti sibi concilium totius Galliae in diem certam indicere.
          Gallia est omnis divisa in partes tres, quarum. Cras mattis iudicium purus sit amet fermentum. Qui ipsorum lingua Celtae, nostra Galli appellantur. Excepteur sint obcaecat cupiditat non proident culpa.
          Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. Quisque ut dolor gravida, placerat libero vel, euismod. Quo usque tandem abutere, Catilina, patientia nostra? A communi observantia non est recedendum. Inmensae subtilitatis, obscuris et malesuada fames. Unam incolunt Belgae, aliam Aquitani, tertiam.»
        text_short: |
          «Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus sit amet orci eget imperdiet. Mauris tristique enim faucibus, lobortis mauris ut, aliquam justo.»
        author_name: Marianna Madia
        author_role: Ministro per la semplificazione e la pubblica amministrazione
    capitoli_title: Gli altri capitoli del piano
    capitoli:
      data-center-e-cloud: Data center e cloud
      connettivita: Connettività
      dati-della-pa: Dati della PA
      piattaforme-abilitanti: Piattaforme abilitanti
      modello-di-interoperabilita: Modello di interoperabilità
      ecositemi: Ecositemi
      strumenti-per-la-generazione-e-la-diffusione-di-servizi-digitali: Strumenti per la generazione e la diffusione di servizi digitali
      sicurezza: Sicurezza
      data-analytics-framework: Data & Analytics Framework
      gestione-del-cambiamento: Gestione del cambiamento
      principi-per-lo-sviluppo-di-progetti-digitali: Principi per lo sviluppo di progetti digitali
      razionalizzazione-della-spesa: Razionalizzazione della spesa
      piano-triennale: Piano Triennale
      modello-strategico: Modello strategico
    temi_title: I capitoli
    modello_intro: Clicca sulla sezione che ti interessa
    partecipa: Partecipa
    forum_intro: Chiunque può partecipare al forum di discussione e contribuire alla diffusione e alla realizzazione del Piano triennale.
    temi:
      servizi-digitali: Servizi digitali
      ecosistemi: Ecositemi
      interoperabilita: Interoperabilità
      piattaforme-abilitanti: Piattaforme abilitanti
      dati: Dati
      rete: Connettività
      cloud: Data center e cloud
      sicurezza: Sicurezza
      big-data: Data & Analytics Framework
      gestione-del-cambiamento: Gestione del cambiamento
